try {
    fx()
} catch (error) {
    console.log(error)
}

try {
    fn()
} catch {
    console.log('Error')
}